version: "3.0"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 85:80
    volumes:
      - .:/var/www/html/
    links:
      - treehost
  treehost:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: tree_user
      MYSQL_PASSWORD: tree_password
      MYSQL_DATABASE: tree_db
      MYSQL_ROOT_PASSWORD: example_tree
      MYSQL_TCP_PORT: 3306
    ports:
      - "3307:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080          